Vagrant.configure("2") do |config|
    config.vm.define "srv-example-02" do |vmexample2|
      vmexample2.vm.box = "centos/7"
      vmexample2.vm.hostname = 'srv-example-02'
      vmexample2.vm.synced_folder "work/", "/work"
      config.vbguest.installer_options = { allow_kernel_upgrade: true }

      vmexample2.vm.network :private_network, ip: "10.0.6.50"

      config.vm.provision "ansible" do |ansible|
        ansible.playbook = "../ansible-scripts/provisioning/playbooks/provisioning.yaml"
        ansible.verbose = true
      end

      vmexample2.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--cpus", 1]
        v.customize ["modifyvm", :id, "--name", "srv-example-02"]
      end
    end
  end
