Vagrant.configure("2") do |config|
  config.vm.define "srv-centos-01" do |srvcentos|
      srvcentos.vm.box = "centos/7"
      srvcentos.vm.hostname = 'srv-centos-01'
      srvcentos.vm.synced_folder "work/", "/work"
      config.vbguest.installer_options = { allow_kernel_upgrade: true }

      srvcentos.vm.network :private_network, ip: "10.0.7.56", auto_config: false

      srvcentos.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--cpus", 1]
        v.customize ["modifyvm", :id, "--name", "srv-centos-01"]
      end
  end
end
